{
  "uid" : "99023da43ecb1abf",
  "name" : "test_invalid_login[nirt236@gmail.com-123456]",
  "fullName" : "tests.test_login.TestLogin#test_invalid_login",
  "historyId" : "759a8709b421dba7c516b861c451e0c7",
  "time" : {
    "start" : 1604104704713,
    "stop" : 1604104707096,
    "duration" : 2383
  },
  "description" : "test invalid login",
  "descriptionHtml" : "<p>test invalid login</p>\n",
  "status" : "broken",
  "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement",
  "statusTrace" : "self = <tests.test_login.TestLogin object at 0x7f5792f95fd0>\ncreate_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"88371206293a4614ce114c93cc2355f1\")>\nemail = 'nirt236@gmail.com', password = '123456'\n\n    @allure.description(\"test invalid login\")\n    @pytest.mark.parametrize(\"email,password\", [(\"nirt236@gmail.com\", \"123456\"), (\"elias@gmail.com\", \"12345Tr\")])\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, create_driver, email, password):\n        ap = AboutPage()\n        ap.click_login_link()\n        lp = LoginPage()\n        lp.login(email, password)\n>       assert_that(lp.get_error_message()).is_equal_to(self._error_msg)\n\ntests/test_login.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:27: in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\npages/base_page.py:40: in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:71: in until\n    value = method(self._driver)\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"88371206293a4614ce114c93cc2355f1\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"88371206293a4614ce114c93cc2355f1\", element=\"8a0dd5df-27a4-4494-aefd-7ebdcb9ca016\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:411: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "prep_properties",
    "time" : {
      "start" : 1604104650312,
      "stop" : 1604104650312,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1604104650223,
      "stop" : 1604104650312,
      "duration" : 89
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "create_driver",
    "time" : {
      "start" : 1604104701057,
      "stop" : 1604104704124,
      "duration" : 3067
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "test invalid login",
    "status" : "broken",
    "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement",
    "statusTrace" : "self = <tests.test_login.TestLogin object at 0x7f5792f95fd0>\ncreate_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"88371206293a4614ce114c93cc2355f1\")>\nemail = 'nirt236@gmail.com', password = '123456'\n\n    @allure.description(\"test invalid login\")\n    @pytest.mark.parametrize(\"email,password\", [(\"nirt236@gmail.com\", \"123456\"), (\"elias@gmail.com\", \"12345Tr\")])\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, create_driver, email, password):\n        ap = AboutPage()\n        ap.click_login_link()\n        lp = LoginPage()\n        lp.login(email, password)\n>       assert_that(lp.get_error_message()).is_equal_to(self._error_msg)\n\ntests/test_login.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:27: in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\npages/base_page.py:40: in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:71: in until\n    value = method(self._driver)\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"88371206293a4614ce114c93cc2355f1\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"88371206293a4614ce114c93cc2355f1\", element=\"8a0dd5df-27a4-4494-aefd-7ebdcb9ca016\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:411: TypeError",
    "steps" : [ {
      "name" : "Click Login link",
      "time" : {
        "start" : 1604104704714,
        "stop" : 1604104705827,
        "duration" : 1113
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Log in with username: 'nirt236@gmail.com' and password: '123456'",
      "time" : {
        "start" : 1604104705828,
        "stop" : 1604104706987,
        "duration" : 1159
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'nirt236@gmail.com'"
      }, {
        "name" : "password",
        "value" : "'123456'"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Get error message",
      "time" : {
        "start" : 1604104706987,
        "stop" : 1604104707096,
        "duration" : 109
      },
      "status" : "broken",
      "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/login_page.py\", line 27, in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 40, in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "5d03236109f7c9e5",
      "name" : "screenshot on failure: 31/10/2020, 00:38:24",
      "source" : "5d03236109f7c9e5.png",
      "type" : "image/png",
      "size" : 519743
    }, {
      "uid" : "a5e745a735dd1041",
      "name" : "screenshot on failure: 31/10/2020, 00:38:27",
      "source" : "a5e745a735dd1041.png",
      "type" : "image/png",
      "size" : 200044
    } ],
    "parameters" : [ ],
    "stepsCount" : 3,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "create_driver::0",
    "time" : {
      "start" : 1604104707428,
      "stop" : 1604104707482,
      "duration" : 54
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "blocker"
  }, {
    "name" : "story",
    "value" : "Login Feature's Functionality"
  }, {
    "name" : "epic",
    "value" : "Security"
  }, {
    "name" : "tag",
    "value" : "security"
  }, {
    "name" : "tag",
    "value" : "run(order=3)"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "fv-az68-995"
  }, {
    "name" : "thread",
    "value" : "4814-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "email",
    "value" : "'nirt236@gmail.com'"
  }, {
    "name" : "password",
    "value" : "'123456'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "blocker",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=3)", "security" ]
  },
  "source" : "99023da43ecb1abf.json",
  "parameterValues" : [ "'nirt236@gmail.com'", "'123456'" ]
}