{
  "uid" : "9a4feee44a1b01d2",
  "name" : "test_invalid_login[elias@gmail.com-12345Tr]",
  "fullName" : "tests.test_login.TestLogin#test_invalid_login",
  "historyId" : "31e205e9028fb72b16f7418e423bbef8",
  "time" : {
    "start" : 1604104711734,
    "stop" : 1604104714002,
    "duration" : 2268
  },
  "description" : "test invalid login",
  "descriptionHtml" : "<p>test invalid login</p>\n",
  "status" : "broken",
  "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement",
  "statusTrace" : "self = <tests.test_login.TestLogin object at 0x7f57953897c0>\ncreate_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"e2e32e683b823c264138f92efa2d465b\")>\nemail = 'elias@gmail.com', password = '12345Tr'\n\n    @allure.description(\"test invalid login\")\n    @pytest.mark.parametrize(\"email,password\", [(\"nirt236@gmail.com\", \"123456\"), (\"elias@gmail.com\", \"12345Tr\")])\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, create_driver, email, password):\n        ap = AboutPage()\n        ap.click_login_link()\n        lp = LoginPage()\n        lp.login(email, password)\n>       assert_that(lp.get_error_message()).is_equal_to(self._error_msg)\n\ntests/test_login.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:27: in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\npages/base_page.py:40: in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:71: in until\n    value = method(self._driver)\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"e2e32e683b823c264138f92efa2d465b\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"e2e32e683b823c264138f92efa2d465b\", element=\"f4c6681f-b5fb-4251-8031-64e38c453489\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:411: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "prep_properties",
    "time" : {
      "start" : 1604104650312,
      "stop" : 1604104650312,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "create_driver",
    "time" : {
      "start" : 1604104707491,
      "stop" : 1604104711174,
      "duration" : 3683
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1604104650223,
      "stop" : 1604104650312,
      "duration" : 89
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "test invalid login",
    "status" : "broken",
    "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement",
    "statusTrace" : "self = <tests.test_login.TestLogin object at 0x7f57953897c0>\ncreate_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"e2e32e683b823c264138f92efa2d465b\")>\nemail = 'elias@gmail.com', password = '12345Tr'\n\n    @allure.description(\"test invalid login\")\n    @pytest.mark.parametrize(\"email,password\", [(\"nirt236@gmail.com\", \"123456\"), (\"elias@gmail.com\", \"12345Tr\")])\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, create_driver, email, password):\n        ap = AboutPage()\n        ap.click_login_link()\n        lp = LoginPage()\n        lp.login(email, password)\n>       assert_that(lp.get_error_message()).is_equal_to(self._error_msg)\n\ntests/test_login.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:27: in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\npages/base_page.py:40: in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:71: in until\n    value = method(self._driver)\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"e2e32e683b823c264138f92efa2d465b\")>\nby = <selenium.webdriver.remote.webelement.WebElement (session=\"e2e32e683b823c264138f92efa2d465b\", element=\"f4c6681f-b5fb-4251-8031-64e38c453489\")>\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n\n/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:411: TypeError",
    "steps" : [ {
      "name" : "Click Login link",
      "time" : {
        "start" : 1604104711735,
        "stop" : 1604104712807,
        "duration" : 1072
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Log in with username: 'elias@gmail.com' and password: '12345Tr'",
      "time" : {
        "start" : 1604104712808,
        "stop" : 1604104713891,
        "duration" : 1083
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "username",
        "value" : "'elias@gmail.com'"
      }, {
        "name" : "password",
        "value" : "'12345Tr'"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Get error message",
      "time" : {
        "start" : 1604104713891,
        "stop" : 1604104714001,
        "duration" : 110
      },
      "status" : "broken",
      "statusMessage" : "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not WebElement\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/login_page.py\", line 27, in get_error_message\n    return self.get_text(self._driver.find_element(*self.LOGIN_ERROR_MESSAGE))\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 40, in get_text\n    el = self._wait.until(expected_conditions.visibility_of_element_located(webelement))\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py\", line 128, in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n  File \"/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "4f515bb9c6b072e7",
      "name" : "screenshot on failure: 31/10/2020, 00:38:31",
      "source" : "4f515bb9c6b072e7.png",
      "type" : "image/png",
      "size" : 520426
    }, {
      "uid" : "4df8e096f21b6e0e",
      "name" : "screenshot on failure: 31/10/2020, 00:38:34",
      "source" : "4df8e096f21b6e0e.png",
      "type" : "image/png",
      "size" : 200044
    } ],
    "parameters" : [ ],
    "stepsCount" : 3,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "create_driver::0",
    "time" : {
      "start" : 1604104714332,
      "stop" : 1604104714386,
      "duration" : 54
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "blocker"
  }, {
    "name" : "story",
    "value" : "Login Feature's Functionality"
  }, {
    "name" : "epic",
    "value" : "Security"
  }, {
    "name" : "tag",
    "value" : "security"
  }, {
    "name" : "tag",
    "value" : "run(order=3)"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "fv-az68-995"
  }, {
    "name" : "thread",
    "value" : "4814-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "email",
    "value" : "'elias@gmail.com'"
  }, {
    "name" : "password",
    "value" : "'12345Tr'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "blocker",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=3)", "security" ]
  },
  "source" : "9a4feee44a1b01d2.json",
  "parameterValues" : [ "'elias@gmail.com'", "'12345Tr'" ]
}